"""
transpiler.py — Synapse → Python/PyTorch Transpiler
"""

from __future__ import annotations

from typing import List

from ast_nodes import (
    ASTNode,
    ASTVisitor,
    AIBlockNode,
    IdentifierNode,
    LayerNode,
    ListNode,
    MemoryNode,
    ModelNode,
    NumberNode,
    PipelineNode,
    ProgramNode,
    StringNode,
    TensorNode,
    TrainConfigNode,
    TrainNode,
)


class TranspileError(Exception):
    pass


ACTIVATION_MAP: dict[str, str] = {
    "relu":      "nn.ReLU()",
    "sigmoid":   "nn.Sigmoid()",
    "tanh":      "nn.Tanh()",
    "softmax":   "nn.Softmax(dim=-1)",
    "leakyrelu": "nn.LeakyReLU()",
    "gelu":      "nn.GELU()",
    "selu":      "nn.SELU()",
}

LAYER_MAP: dict[str, str] = {
    "dense":     "nn.Linear",
    "linear":    "nn.Linear",
    "conv2d":    "nn.Conv2d",
    "conv1d":    "nn.Conv1d",
    "flatten":   "nn.Flatten",
    "dropout":   "nn.Dropout",
    "batchnorm": "nn.BatchNorm1d",
    "lstm":      "nn.LSTM",
    "gru":       "nn.GRU",
    "embedding": "nn.Embedding",
    "attention": "nn.MultiheadAttention",
}


class CodeBuffer:
    def __init__(self) -> None:
        self._lines: List[str] = []
        self._indent: int = 0

    def indent(self) -> None:
        self._indent += 1

    def dedent(self) -> None:
        self._indent = max(0, self._indent - 1)

    def emit(self, line: str = "") -> None:
        prefix = "    " * self._indent
        self._lines.append(f"{prefix}{line}")

    def blank(self) -> None:
        self._lines.append("")

    def get(self) -> str:
        return "\n".join(self._lines)


class Transpiler(ASTVisitor):

    def __init__(self) -> None:
        self._buf = CodeBuffer()

    def transpile(self, program: ProgramNode) -> str:
        self._buf = CodeBuffer()
        self._emit_header()
        for stmt in program.statements:
            self.visit(stmt)
            self._buf.blank()
        self._emit_footer()
        return self._buf.get()

    def _emit_header(self) -> None:
        self._buf.emit("# ============================================================")
        self._buf.emit("# Generated by Synapse v1 — do not edit by hand")
        self._buf.emit("# ============================================================")
        self._buf.blank()
        self._buf.emit("import torch")
        self._buf.emit("import torch.nn as nn")
        self._buf.emit("import torch.optim as optim")
        self._buf.blank()

    def _emit_footer(self) -> None:
        self._buf.blank()
        self._buf.emit("if __name__ == '__main__':")
        self._buf.indent()
        self._buf.emit("main()")
        self._buf.dedent()

    def visit_TensorNode(self, node: TensorNode) -> None:
        value_expr = self._expr_to_str(node.value)
        device_str = f", device='{node.device}'" if node.device else ""
        self._buf.emit(
            f"{node.name} = torch.tensor({value_expr}, dtype=torch.float32{device_str})"
        )

    def visit_ModelNode(self, node: ModelNode) -> None:
        self._buf.emit(f"class {node.name}(nn.Module):")
        self._buf.indent()

        self._buf.emit("def __init__(self):")
        self._buf.indent()
        self._buf.emit(f"super({node.name}, self).__init__()")
        self._buf.emit("self.network = nn.Sequential(")
        self._buf.indent()
        for layer in node.layers:
            for line in self._layer_to_lines(layer):
                self._buf.emit(line)
        self._buf.dedent()
        self._buf.emit(")")
        self._buf.dedent()

        self._buf.blank()
        self._buf.emit("def forward(self, x):")
        self._buf.indent()
        self._buf.emit("return self.network(x)")
        self._buf.dedent()

        self._buf.dedent()

    def _layer_to_lines(self, node: LayerNode) -> List[str]:
        layer_key = node.layer_type.lower()
        lines: List[str] = []

        if layer_key in ("dense", "linear"):
            args = [self._expr_to_str(a) for a in node.args]
            if not args:
                raise TranspileError("Layer 'dense' requires at least 1 argument (out_features)")
            lines.append(f"nn.LazyLinear({args[0]}),")
            if len(args) >= 2:
                act_name = args[1].strip("'\"").lower()
                act_expr = ACTIVATION_MAP.get(act_name)
                if act_expr is None:
                    raise TranspileError(
                        f"Unknown activation: {act_name!r}. "
                        f"Supported: {list(ACTIVATION_MAP.keys())}"
                    )
                lines.append(f"{act_expr},")

        elif layer_key == "dropout":
            args = [self._expr_to_str(a) for a in node.args]
            p = args[0] if args else "0.5"
            lines.append(f"nn.Dropout(p={p}),")

        elif layer_key == "flatten":
            lines.append("nn.Flatten(),")

        elif layer_key == "conv2d":
            args = [self._expr_to_str(a) for a in node.args]
            lines.append(f"nn.LazyConv2d({', '.join(args)}),")

        elif layer_key == "batchnorm":
            lines.append("nn.LazyBatchNorm1d(),")

        else:
            pt_class = LAYER_MAP.get(layer_key, f"nn.{node.layer_type}")
            args = [self._expr_to_str(a) for a in node.args]
            lines.append(f"{pt_class}({', '.join(args)}),")

        return lines

    def visit_TrainNode(self, node: TrainNode) -> None:
        config: dict[str, ASTNode] = {c.key: c.value for c in node.config}

        epochs_node = config.get("epochs")
        epochs = self._expr_to_str(epochs_node) if epochs_node else "1"

        lr_node = config.get("lr", config.get("learning_rate"))
        lr = self._expr_to_str(lr_node) if lr_node else "1e-3"

        loss_node = config.get("loss")
        loss_fn = self._loss_to_str(self._expr_to_str(loss_node)) if loss_node else "nn.MSELoss()"

        opt_node = config.get("optimizer")
        opt_name = self._expr_to_str(opt_node).strip("'\"").lower() if opt_node else "adam"
        opt_class = self._optimizer_to_str(opt_name)

        input_var = "_synapse_input"

        self._buf.emit("def main():")
        self._buf.indent()

        self._buf.emit(f"# --- Training: {node.model_name} on {node.data_name} ---")
        self._buf.emit(f"_model = {node.model_name}()")
        self._buf.emit(f"_criterion = {loss_fn}")
        self._buf.emit(f"_optimizer = {opt_class}(_model.parameters(), lr={lr})")
        self._buf.blank()
        self._buf.emit(f"{input_var} = {node.data_name}.clone()")
        self._buf.emit(f"if {input_var}.dim() == 1:")
        self._buf.indent()
        self._buf.emit(f"{input_var} = {input_var}.unsqueeze(0)")
        self._buf.dedent()
        self._buf.blank()
        self._buf.emit(f"print(f'Training {node.model_name} for {{{epochs}}} epoch(s)...')")
        self._buf.emit(f"for _epoch in range({epochs}):")
        self._buf.indent()
        self._buf.emit("_optimizer.zero_grad()")
        self._buf.emit(f"_output = _model({input_var})")
        self._buf.emit("_loss = _criterion(_output, _output.detach())")
        self._buf.emit("_loss.backward()")
        self._buf.emit("_optimizer.step()")
        self._buf.emit(
            f"print(f'  Epoch {{_epoch+1}}/{{{epochs}}} --- loss: {{_loss.item():.6f}}')"
        )
        self._buf.dedent()

        self._buf.emit("print('Training complete.')")
        self._buf.dedent()

    def visit_AIBlockNode(self, node: AIBlockNode) -> None:
        raise TranspileError("AIBlockNode is not yet implemented in Synapse v1.")

    def visit_MemoryNode(self, node: MemoryNode) -> None:
        raise TranspileError("MemoryNode is not yet implemented in Synapse v1.")

    def visit_PipelineNode(self, node: PipelineNode) -> None:
        raise TranspileError("PipelineNode is not yet implemented in Synapse v1.")

    def generic_visit(self, node: ASTNode) -> None:
        raise TranspileError(f"No transpiler rule for: {type(node).__name__}")

    def _expr_to_str(self, node: ASTNode) -> str:
        if isinstance(node, NumberNode):
            return str(node.value)
        if isinstance(node, StringNode):
            return repr(node.value)
        if isinstance(node, IdentifierNode):
            return node.name
        if isinstance(node, ListNode):
            elements = ", ".join(self._expr_to_str(e) for e in node.elements)
            return f"[{elements}]"
        raise TranspileError(f"Cannot serialise: {type(node).__name__}")

    @staticmethod
    def _loss_to_str(name: str) -> str:
        mapping = {
            "mse":          "nn.MSELoss()",
            "crossentropy": "nn.CrossEntropyLoss()",
            "bce":          "nn.BCELoss()",
            "l1":           "nn.L1Loss()",
            "huber":        "nn.HuberLoss()",
        }
        return mapping.get(name.strip("'\"").lower(), "nn.MSELoss()")

    @staticmethod
    def _optimizer_to_str(name: str) -> str:
        mapping = {
            "adam":    "optim.Adam",
            "sgd":     "optim.SGD",
            "adamw":   "optim.AdamW",
            "rmsprop": "optim.RMSprop",
        }
        return mapping.get(name.lower(), "optim.Adam")


def transpile(program: ProgramNode) -> str:
    return Transpiler().transpile(program)
